# Generated by Django 4.2.3 on 2023-08-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_lga_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='pharmacy_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
