# Generated by Django 4.2.3 on 2023-08-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_category_image_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
