# Generated by Django 4.2.3 on 2023-08-12 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_drug_drug_image_drug_images_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
