# Generated by Django 4.2.3 on 2023-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_prescription_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='is_prescription_needed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
